title: Thai Nang Tani Politics Observatory
markdown: kramdown
theme: minima

# Force rebuild
force_rebuild: 59

# Make sure Jekyll includes the images folder
include:
  - images

# Disable minima's default collections/static overrides
collections: {}
